config/routes.rb
Rails.application.routes.draw do
  resources :vsets

  resources :velements

end

app/models/velement.rb
class Velement < ActiveRecord::Base
  has_and_belongs_to_many :vsets
end

app/models/vset.rb
class Vset < ActiveRecord::Base
  has_and_belongs_to_many :velements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/velements_controller.rb
class VelementsController < ApplicationController
  before_action :set_velement, only: [:show, :edit, :update, :destroy]

  # GET /velements
  # GET /velements.json
  def index
    @velements = Velement.all
  end

  # GET /velements/1
  # GET /velements/1.json
  def show
  end

  # GET /velements/new
  def new
    @velement = Velement.new
  end

  # GET /velements/1/edit
  def edit
  end

  # POST /velements
  # POST /velements.json
  def create
    @velement = Velement.new(velement_params)

    respond_to do |format|
      if @velement.save
        format.html { redirect_to @velement, notice: 'Velement was successfully created.' }
        format.json { render :show, status: :created, location: @velement }
      else
        format.html { render :new }
        format.json { render json: @velement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /velements/1
  # PATCH/PUT /velements/1.json
  def update
    respond_to do |format|
      if @velement.update(velement_params)
        format.html { redirect_to @velement, notice: 'Velement was successfully updated.' }
        format.json { render :show, status: :ok, location: @velement }
      else
        format.html { render :edit }
        format.json { render json: @velement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /velements/1
  # DELETE /velements/1.json
  def destroy
    @velement.destroy
    respond_to do |format|
      format.html { redirect_to velements_url, notice: 'Velement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_velement
      @velement = Velement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def velement_params
      params.require(:velement).permit(:name)
    end
end

app/controllers/vsets_controller.rb
class VsetsController < ApplicationController
  before_action :set_vset, only: [:show, :edit, :update, :destroy]

  # GET /vsets
  # GET /vsets.json
  def index
    @vsets = Vset.all
  end

  # GET /vsets/1
  # GET /vsets/1.json
  def show
  end

  # GET /vsets/new
  def new
    @vset = Vset.new
  end

  # GET /vsets/1/edit
  def edit
  end

  # POST /vsets
  # POST /vsets.json
  def create
    @vset = Vset.new(vset_params)

    respond_to do |format|
      if @vset.save
        format.html { redirect_to @vset, notice: 'Vset was successfully created.' }
        format.json { render :show, status: :created, location: @vset }
      else
        format.html { render :new }
        format.json { render json: @vset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vsets/1
  # PATCH/PUT /vsets/1.json
  def update
    respond_to do |format|
      if @vset.update(vset_params)
        format.html { redirect_to @vset, notice: 'Vset was successfully updated.' }
        format.json { render :show, status: :ok, location: @vset }
      else
        format.html { render :edit }
        format.json { render json: @vset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vsets/1
  # DELETE /vsets/1.json
  def destroy
    @vset.destroy
    respond_to do |format|
      format.html { redirect_to vsets_url, notice: 'Vset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vset
      @vset = Vset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vset_params
      params.require(:vset).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/velements_helper.rb
module VelementsHelper
end

app/helpers/vsets_helper.rb
module VsetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Venn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/velements/_form.html.erb
<%= form_for(@velement) do |f| %>
  <% if @velement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@velement.errors.count, "error") %> prohibited this velement from being saved:</h2>

      <ul>
      <% @velement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/velements/edit.html.erb
<h1>Editing velement</h1>

<%= render 'form' %>

<%= link_to 'Show', @velement %> |
<%= link_to 'Back', velements_path %>

app/views/velements/index.html.erb
<h1>Listing velements</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @velements.each do |velement| %>
      <tr>
        <td><%= velement.name %></td>
        <td><%= link_to 'Show', velement %></td>
        <td><%= link_to 'Edit', edit_velement_path(velement) %></td>
        <td><%= link_to 'Destroy', velement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Velement', new_velement_path %>

app/views/velements/new.html.erb
<h1>New velement</h1>

<%= render 'form' %>

<%= link_to 'Back', velements_path %>

app/views/velements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @velement.name %>
</p>

<%= link_to 'Edit', edit_velement_path(@velement) %> |
<%= link_to 'Back', velements_path %>

app/views/vsets/_form.html.erb
<%= form_for(@vset) do |f| %>
  <% if @vset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vset.errors.count, "error") %> prohibited this vset from being saved:</h2>

      <ul>
      <% @vset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vsets/edit.html.erb
<h1>Editing vset</h1>

<%= render 'form' %>

<%= link_to 'Show', @vset %> |
<%= link_to 'Back', vsets_path %>

app/views/vsets/index.html.erb
<h1>Listing vsets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vsets.each do |vset| %>
      <tr>
        <td><%= vset.name %></td>
        <td><%= link_to 'Show', vset %></td>
        <td><%= link_to 'Edit', edit_vset_path(vset) %></td>
        <td><%= link_to 'Destroy', vset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vset', new_vset_path %>

app/views/vsets/new.html.erb
<h1>New vset</h1>

<%= render 'form' %>

<%= link_to 'Back', vsets_path %>

app/views/vsets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vset.name %>
</p>

<%= link_to 'Edit', edit_vset_path(@vset) %> |
<%= link_to 'Back', vsets_path %>